<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<RootNamespace>Afetto_.Net.Tests.Unit</RootNamespace>
		<InternalsVisibleTo>Afetto-.Net.Tests.Integration</InternalsVisibleTo>
	</PropertyGroup>

	<ItemGroup>
		<!-- xUnit -->
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.12" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.9.0" />
		<PackageReference Include="Oracle.EntityFrameworkCore" Version="9.23.60" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
		<PackageReference Include="xunit" Version="2.9.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />

		<!-- Moq para mocking -->
		<PackageReference Include="Moq" Version="4.20.72" />

		<!-- FluentAssertions para asserts mais legíveis -->
		<PackageReference Include="FluentAssertions" Version="6.12.1" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Afetto-.Net.Tests.Integration" />
	</ItemGroup>
</Project>