// <auto-generated />
using System;
using Afetto_.Net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Afetto.Net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522180823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Afetto_.Net.Models.Bairro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_BAIRRO");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_CIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("TB_BAIRRO", (string)null);
                });

            modelBuilder.Entity("Afetto_.Net.Models.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_CIDADE");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("TB_CIDADE", (string)null);
                });

            modelBuilder.Entity("Afetto_.Net.Models.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PAIS");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("SIGLA");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("TB_ESTADO", (string)null);
                });

            modelBuilder.Entity("Afetto_.Net.Models.Logradouro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_LOGRADOURO");

                    b.Property<Guid>("BairroId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_BAIRRO");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("CEP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.ToTable("TB_LOGRADOURO", (string)null);
                });

            modelBuilder.Entity("Afetto_.Net.Models.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PAIS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("SIGLA");

                    b.HasKey("Id");

                    b.ToTable("TB_PAIS", (string)null);
                });

            modelBuilder.Entity("Afetto_.Net.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_NASC");

                    b.Property<string>("Descricao")
                        .HasColumnType("CLOB")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<float>("Peso")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("PESO");

                    b.Property<string>("QrCodeToken")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("QR_CODE_TOKEN");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RACA");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("SEXO");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("QrCodeToken")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_PET", (string)null);
                });

            modelBuilder.Entity("Afetto_.Net.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_NASC");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<Guid>("LogradouroId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_LOGRADOURO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LogradouroId");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("Afetto_.Net.Models.Bairro", b =>
                {
                    b.HasOne("Afetto_.Net.Models.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Cidade", b =>
                {
                    b.HasOne("Afetto_.Net.Models.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Estado", b =>
                {
                    b.HasOne("Afetto_.Net.Models.Pais", "Pais")
                        .WithMany("Estados")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Logradouro", b =>
                {
                    b.HasOne("Afetto_.Net.Models.Bairro", "Bairro")
                        .WithMany("Logradouros")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Pet", b =>
                {
                    b.HasOne("Afetto_.Net.Models.Usuario", "Usuario")
                        .WithMany("Pets")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Usuario", b =>
                {
                    b.HasOne("Afetto_.Net.Models.Logradouro", "Logradouro")
                        .WithMany("Usuarios")
                        .HasForeignKey("LogradouroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Bairro", b =>
                {
                    b.Navigation("Logradouros");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Cidade", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Logradouro", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Pais", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("Afetto_.Net.Models.Usuario", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
